function inputValidation() {
    // Private properties
    var Nes = require('nes/client');
    var nesClient = new Nes.Client('ws://localhost:3000');


    // Private methods
    function countRows() {
        var counter = 0;

        nesClient.connect(function (err) {
            nesClient.request('hello', function (err, payload) {
                // do something with payload
                console.log(payload);
            });
        });

        return counter;
    }

    // Private objects
    // userdata generated by input-forms


    // ___________________________________________________________
    // Public methods
    var validationObject = {

        validateInput: function (event) {
            console.log(countRows);
        }

    }

    return validationObject;
}

// Event handler
(function () {
    var inputValidator = new inputValidation();
    document.forms.signup.addEventListener('submit', inputValidator.validateInput, false);
    // document.forms.login.addEventListener('submit', inputValidator.validateInput, false);
    // document.forms.userdata.addEventListener('submit', inputValidator.validateInput, false);
    // document.forms.addUser.addEventListener('submit', inputValidator.validateInput, false);
    // document.forms.removeUser.addEventListener('submit', inputValidator.validateInput, false);
}());
